name: rdflib
description:
  A pure Dart package for working with RDF (resource description framework).
version: 0.2.0
homepage: https://github.com/anusii/rdflib
repository: https://github.com/anusii/rdflib

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  logging: ^1.1.0
  encrypt: ^5.0.1
  crypto: ^3.0.2
  petitparser: ^5.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
