name: rdfgraph
description:
  A dart toolkit for organizing RDF files (inspired by RDFLib).
  Use the graph to store triples, read RDF files and export to different formats.
version: 0.0.10
homepage: https://github.com/anusii/rdfgraph
repository: https://github.com/anusii/rdfgraph

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  logging: ^1.0.2

dev_dependencies:
