name: rdflib
description:
  A pure Dart package for working with RDF (resource description framework).
version: 0.1.4
homepage: https://github.com/anusii/rdflib
repository: https://github.com/anusii/rdflib

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  logging: ^1.0.2

dev_dependencies:
